version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: .circleci/install.sh
      - run:
          name: Build project
          command: .circleci/build.sh
